image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - unpublished.sourcekit-lsp@0.0.1:NJBDyUtdIfPBJcBUYsntWQ==
    - cgrevisse.swift-project-creation@0.0.3:NKCFbFRhkgtDti+m0kFH3Q==
    - vadimcn.vscode-lldb@1.4.5:lwHCNwtm0kmOBXeQUIPGMQ==tasks:
- command: swift --version